### ISSUE TITLE
Always setting Content-Type header to application/json triggers CORS preflight requirement

### ISSUE THREAD

**Issue by jzaefferer** [masylum/mobx-rest-fetch-adapter#8]
Testing mobx-rest I was wondering why all GET requests ended up with preflight requests. According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS requests with a Content-Type header 'application/json' aren't CORS safe-listed.

With that in mind, why is that header always being set? https://github.com/masylum/mobx-rest-fetch-adapter/blob/a5f3d7a82c34075603f3a13a719d9ff41b6e6832/src/index.js#L32

Comparing to the jQuery adapter, it doesn't explicitly set the same header: https://github.com/masylum/mobx-rest-jquery-adapter/blob/master/src/index.js and according to http://api.jquery.com/jQuery.ajax/ it defaults to 'application/x-www-form-urlencoded', which is acceptable for non-preflight CORS requests.

**Comment by masylum** [comment]
Could you propose a PR? I'm now on paternal leave 👶 so I don't have much time, but this seems important enough to get fixed 👌
